[ADD] l10n_pt_account for v9
OCA/l10n-portugal pull request #13
Opened 2015-12-10 17:20 UTC by thinkopen-pt

After the submission of our previous version of this module, Odoo v9 has been released and so are re-submitting the module, while taking notice of the suggestions kindly offered by the reviewers of the other PR.

These commits also remove the LICENSE file from the base of the repository, as we believe each module should be allowed to have its own license.

2015-12-17 22:09 UTC, dreispt commented
@andreparames Please make mr .Travis happy...

2015-12-17 22:10 UTC, dreispt commented on l10n_pt_account/__openerp__.py
> +    'version': '1.122',
Use format 9.0.x.y.z

2015-12-17 22:13 UTC, dreispt commented on l10n_pt_account/__openerp__.py
> +                'stock_account',
Can this module be split in smaller ones? Purchase related features depend on purchase, sale features depend on sale, etc...

2015-12-17 22:14 UTC, dreispt commented on l10n_pt_account/__openerp__.py
> +    'test': [],
remove unused keys

2015-12-17 22:14 UTC, dreispt commented on l10n_pt_account/__openerp__.py
> +    'active': True,
active is deprecated

2015-12-17 22:15 UTC, dreispt commented on l10n_pt_account/account_config.py
> +# -*- coding: utf-8 -*-
Add copyright and license. There is a short form in the template at oca/maintainer-tools

2015-12-17 22:16 UTC, dreispt commented on l10n_pt_account/__openerp__.py
> +    'description': '''Customization of Accounting for Portugal.
Move the description into a README.rst file.
Please use the template at OCA/maintainer-tools

2016-07-18 16:51 UTC, dreispt commented
@andreparames I believe that you have a later version of this code correct? is it for 9.0?
 If so, it's pointless to continue review this PR - can you create a new one with the latest code?

2016-09-15 10:42 UTC, thinkopen-pt commented
The new changes have been submitted to this branch, along with a few cleanups.

2016-09-15 10:50 UTC, dreispt commented on l10n_pt_account/__init__.py
> +# Copyright 2010-2016 ThinkOpen Solutions
Missing license; move it up before any line of code

2016-09-15 10:51 UTC, dreispt commented on l10n_pt_account/__openerp__.py
> +    'description': '''Customization of Accounting for Portugal.
Remove description, the README will be used

2016-09-15 10:51 UTC, dreispt commented on l10n_pt_account/__openerp__.py
> +# Copyright 2010-2016 ThinkOpen Solutions
Same as above

2016-09-15 10:51 UTC, dreispt commented on l10n_pt_account/__openerp__.py
> +    'init_xml': [],
Deprecated, remove

2016-09-15 10:51 UTC, dreispt commented on l10n_pt_account/__openerp__.py
> +    'update_xml': ['security/account_security.xml',
Deprecated, change to `data`

2016-09-15 10:52 UTC, dreispt commented on l10n_pt_account/__openerp__.py
> +    'active': True,
Deprecated, remove

2016-09-15 10:52 UTC, dreispt commented on l10n_pt_account/account_config.py
> +# Copyright 2010-2016 ThinkOpen Solutions
Add `# -*- coding: utf-8 -*` and proper license line

2016-09-15 10:57 UTC, dreispt commented
Hi, pylint-odoo found a list of good practices and style conventions to fix. Check https://travis-ci.org/OCA/l10n-portugal/jobs/160128728#L425

2016-09-15 10:58 UTC, dreispt commented
The mudule fails to install. Can you check that? For details check https://travis-ci.org/OCA/l10n-portugal/jobs/160128729#L743

2016-09-15 11:00 UTC, dreispt reviewed
These are some initial comments, but all these are checked by pylint-odoo, so you will have a more exhaustive list from the Lint check made on TravisCI.

2016-09-15 21:49 UTC, dreispt commented on l10n_pt_account/account_invoice.py
>  ##############################################################################
You can remove the long disclaimer below.

2016-09-15 21:49 UTC, dreispt commented on l10n_pt_account/wizard/account_pt_invoice_refund.py
>  # -*- coding: utf-8 -*-
s/encoding/coding

2016-10-12 08:58 UTC, andreparames commented
@dreispt sorry, Travis seems to be complaining that an object lacks access rules, but it's an inherited object, so the access rules are already defined in the parent module. Is this a bug in the check, or am I missing something? Thanks.

2016-10-12 09:55 UTC, dreispt requested changes

2016-10-12 09:55 UTC, dreispt commented on l10n_pt_account/stock.py
>              context = {}
With the new API, taking care of the context not only is not necessary, but it will error, since it is read only now.

2016-10-12 09:55 UTC, dreispt commented on l10n_pt_account/account_payment.py
> +from openerp.addons.l10n_pt_acount.report.amount_to_text_pt import amount_to_text
Prefer using `from .report import amount_to_text`

2016-10-12 09:55 UTC, dreispt commented on l10n_pt_account/account_config.py
> +    _inherit = 'account.config.settings'
@andreparames Isn't `account.config.settings` a wizard? It should rather be a `models.TransientModel` then.

2016-10-12 13:04 UTC, dreispt commented
@andreparames Please also check the lint warnings on the TravisCI log.
The tab-vs-spaces are not an issue, but using the old API unless really necessary is.

2016-12-12 22:50 UTC, dreispt requested changes
It's almost there, but there are still a few references to the old AIPi (osv) that need to be removed.

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/guia.py
> +    return d in (easter, sexta_feira_santa)
As a future improvement, holidays could be moved to their own module, and local holidays could then be added.

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/res_config_view.xml
> +</openerp>
Is this a WIP?

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/sale.py
> +        credit notes"""
Please make sure there an Issue was opened, and refer to it here.
Or even better, make a PR for OCB.

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/security/account_security.xml
> +           <field name="name">Accounting / TKO Guias</field>
Please remove TKO branding

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/stock.py
> +from openerp.osv import fields, osv
Importing from osv is deprecated.
Please fix.

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/wizard/stock_create_waybill.py
> +from openerp.osv import fields, osv
Don't import osv. Please fix.

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/wizard/stock_create_waybill.py
> +StockPickingWaybill()
Remove this line.

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/wizard/stock_invoice_onshipping.py
> +from openerp.osv import osv
Don't import from osv. Please fix.

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/wizard/stock_simplified_invoice_onshipping.py
> +from openerp.osv import fields, osv
Don't import from osv. Please fix.

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/wizard/waybill_invoice.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl)./
Remove traiilig `/`

2016-12-12 22:50 UTC, dreispt commented on l10n_pt_account/wizard/waybill_invoice.py
> +from openerp.osv import fields, osv
Don't import from osv. Please fix.

2016-12-13 12:35 UTC, dreispt commented
Notice that the CI tests are failing.
Lint logs: https://travis-ci.org/OCA/l10n-portugal/jobs/183559305#L300

2017-01-02 09:31 UTC, dreispt commented
Travis is still red.

2017-01-06 15:14 UTC, dreispt commented
Ping!

2017-01-28 10:34 UTC, dreispt commented
Will you continue work on this?

2021-11-28 12:13 UTC, closed without merging