15.0 mig l10n pt account invoicexpress
OCA/l10n-portugal pull request #73
Opened 2022-07-25 08:43 UTC by heliaktiv

2022-08-10 20:26 UTC, dreispt commented
Thank you!

2022-08-10 20:30 UTC, dreispt requested changes

2022-08-10 20:30 UTC, dreispt commented on l10n_pt_account_invoicexpress/data/mail_template.xml
> +                    Enviamos em anexo a fatura ${object.name | safe}
With v15 email templates needs to converted to QWeb syntax.

2022-08-10 20:33 UTC, dreispt commented
Something wring found in the tests. Could be a pre-existing bug surfaced now:
```
ValueError: Wrong @depends on '_compute_invoicexpress_doc_type' (compute method of field account.move.invoicexpress_doc_type). Dependency field 'partner_shipping_id' not found in model account.move.
```

2023-04-20 20:43 UTC, rafaelbn commented
Hello @heliaktiv can you please review comments from @dreispt ? Thank you!! 🙏 😄

2024-01-07 12:16 UTC, closed without merging